FROM haproxy
COPY haproxy.cfg /usr/local/etc/haproxy/haproxy.cfg
# USER www-data
# RUN apt-get update && apt-get install -y  rsyslog
# CMD /etc/init.d/rsyslog start && /usr/local/etc/haproxy start && tail -F /var/log/haproxy.log


# CMD service rsyslog start
# COPY log /dev/log